<?xml version="1.0"?>
<package format="3">
  <name>fyp_exploration</name>
  <version>0.0.1</version>
  <description>Frontier detection and visualisation for autonomous exploration.</description>

  <maintainer email="sam@example.com">sam</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>action_msgs</depend>
  <depend>tf2_ros</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
