experiment_bag_recorder:
  ros__parameters:
    log_root_dir: ~/Sam/fyp_ws/logs
    use_latest_detector_run_dir: true

    topics:
      - /tf
      - /tf_static
      - /odom
      - /exploration_grid
      - /projected_map
      - /occupied_cells_vis_array

      - /selected_frontier_goal
      - /frontier_path
      - /frontier_goals
      - /frontier_cells
      - /frontier_markers
      - /frontier_regions_markers
      - /frontier_detector/status

      - /exploration_supervisor/status
      - /exploration_supervisor/recovery_state
      - /exploration_supervisor/recovery_target_goal

      - /exploration_goal_arbiter/status
      - /nav2_frontier_goal_selector/status
      - /selected_exploration_goal
      - /selected_exploration_path
      - /selected_exploration_mode

      - /mapPath
