icp_odometry:
  ros__parameters:
    qos: 2
    wait_for_transform: 0.2

    Icp/PointToPlane: "true"
    Icp/Iterations: "10"
    Icp/VoxelSize: "0.05"
    Icp/Epsilon: "0.001"
    Icp/PointToPlaneK: "20"
    Icp/PointToPlaneRadius: "0"
    Icp/MaxTranslation: "0.2"
    Icp/MaxRotation: "0.78"
    Icp/MaxCorrespondenceDistance: "0.10"
    Icp/Strategy: "1"
    Icp/OutlierRatio: "0.85"
    Icp/CorrespondenceRatio: "0.30"

    Odom/ScanKeyFrameThr: "0.4"
    OdomF2M/ScanSubtractRadius: "0.05"
    OdomF2M/ScanMaxSize: "15000"
    OdomF2M/BundleAdjustment: "false"